#!/usr/bin/python3

"""Twitter-Bot für die Expansion von DS100-Abkürzungen und ähnlichen Abkürzungslisten"""

import argparse

from AnswerMachine import handle_list
from Externals import setup_database, set_twitter_arguments, setup_twitter
import Persistence
import Persistence.log as log

def arguments():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--verbose', '-v',
                        dest='verbose',
                        help='Output lots of stuff',
                        required=False,
                        action='count')
    set_twitter_arguments(parser)
    parser.add_argument('--no-version',
                        dest='notify_version',
                        help='Do not send out version tweet and do not store last version',
                        required=False,
                        action='store_false',
                        default=True)
    args_ = parser.parse_args()
    if args_.verbose is None:
        args_.verbose = 0
    args_.verbose = 50 - args_.verbose * 10
    return args_

def setup_log(loglvl):
    if loglvl <= 0:
        loglvl = 1

    log.basicConfig(level=loglvl, style='{')
    return log.getLogger('ds100')

def teardown_apis(db, notify, max_id_=0):
    if notify:
        Persistence.store_version(db)
    if max_id > 0:
        Persistence.store_since_id(db, max_id_)
    db.close_sucessfully()
    log_.info("Bot finished")

if __name__ == "__main__":
    args = arguments()
    log_ = setup_log(args.verbose)
    try:
        twitter = setup_twitter(args)
        database = setup_database(args)
        if args.notify_version:
            Persistence.notify_new_version(twitter, database)
    except RuntimeError as re:
        log_.critical(re)
        raise SystemExit(1) from re

    tagsearch, magic_tags = database.magic_hashtags()
    max_id = handle_list(twitter.all_relevant_tweets(
                            Persistence.get_since_id(database), tagsearch
                         ),
                         twitter=twitter,
                         database=database,
                         magic_tags=magic_tags)
    teardown_apis(database, args.notify_version, max_id)
