#!/usr/bin/python3

from database import Database
import argparse
import sys

parser = argparse.ArgumentParser(description='Hilfsprogramm zur Verwaltung der DS100-Bot-Blackliste.')
parser.add_argument('--list', action='store_true', required=False, default=False)
parser.add_argument('--add', action='store', required=False)
# parser.add_argument('--remove', action='store', required=False)
parser.add_argument('--statistics-for', action='store', required=False)
parser.add_argument('--verbose', '-v',
                    dest='verbose',
                    help='Output lots of stuff',
                    required=False,
                    action='count')
args = parser.parse_args()
if args.verbose is None:
    args.verbose = 0

sql = Database('readwrite')

if args.list:
    sql.cursor.execute("""
        SELECT
            source,
            Abk
        FROM
            blacklist
    """)
    for row in sql.cursor.fetchall():
        print(row['source'], row['Abk'])
    sys.exit(0)
if not args.statistics_for is None:
    print("Statistics for", args.statistics_for)
    sql.cursor.execute("""
        SELECT
            count(status) as c,
            status
        FROM
            requests
        WHERE
            ds100_id LIKE ?
        GROUP BY
            status
    """, (args.statistics_for, ))
    tot_sum = 0
    for row in sql.cursor.fetchall():
        tot_sum += row['c']
        print(row['c'], row['status'])
    print(tot_sum, "total")
    sys.exit(0)
if not args.add is None:
    sql.cursor.execute("""
        SELECT
            1
        FROM
            blacklist
        JOIN
            sourceflags
        ON
            sourceflags.sourcename = blacklist.source
        WHERE
            abbr || ':' || Abk = ?
    """, (args.add, ))
    row = sql.cursor.fetchone()
    if row is None:
        a = sql.cursor.execute("""
            INSERT INTO
                blacklist(source, Abk)
            SELECT
                sourcename, Abk
            FROM
                sourceflags
            JOIN
                shortstore
            ON
                sourcename = source
            WHERE
                sigil || abbr || ':' || Abk = ?
        """, (args.add,))
        if sql.cursor.rowcount == 0:
            print("Keine Daten eingetragen", file=sys.stderr)
            sys.exit(1)
        else:
            print("Erfolgreich eingetragen!")
            sql.close_sucessfully()
            sys.exit(0)
    else:
        print("Schon eingetragen!")
        sys.exit(0)
