#!/usr/bin/python3

'''Helper for tweeting bot statistics'''

import argparse
import datetime
from Externals import setup_database, set_twitter_arguments, setup_twitter
import Mock
import Persistence.log as log

one_day = datetime.timedelta(days=1)
today = datetime.date.today()
first = today.replace(day=1)
january_first = first.replace(month=1)
first_last_month = (first - one_day).strftime("%Y%m01")
first_last_year = (january_first - one_day).strftime("%Y0101")

parser = argparse.ArgumentParser(description=__doc__)
set_twitter_arguments(parser)
parser.add_argument('--verbose', '-v',
                    dest='verbose',
                    help='Output lots of stuff',
                    required=False,
                    action='count')
parser.add_argument('--since',
                    dest='since',
                    help='Time frame for statistics',
                    required=False,
                    default=0)
args = parser.parse_args()

if args.verbose is None:
    args.verbose = 1
loglvl = 50 - args.verbose * 10
if loglvl <= 0:
    loglvl = 1

log.basicConfig(level=loglvl, style='{')
log_ = log.getLogger('statistics')

since = None
since_text = None
if args.since == 0 or args.since == "0":
    since = 0
    since_text = 'Beginn'
elif args.since == 'month':
    since = first_last_month
    since_text = 'Anfang letzten Monats'
elif args.since == 'year':
    since = first_last_year
    since_text = 'Anfang letzten Jahres'
else:
    since = int(args.since)
    since_text = since

twapi = setup_twitter(args)
if twapi is None:
    twapi = Mock.MockApi()
sql = setup_database(args)

counts = sql.count_status(since=since)
text = f"""Zeit für Statistik! Daten für die Zeit seit {since_text}. Ich habe:
• {counts.get('found', 0)} Kürzel beantwortet, für
• {counts.get('notfound', 0)} Kürzel keine lange Version erkannt und
• {counts.get('blacklist', 0)} nicht beantwortet, weil sie auf der Blacklist standen.

Die populärsten Kürzel waren:
"""

for row in sql.popular_abbrs(since):
    text += f"• {row['S']} ({row['C']}×)\n\u200b"
text += """
Die populärsten Quellen waren:
"""
for row in sql.popular_sources(since):
    text += f"• {row['S']} ({row['C']}×)\n\u200b"
text += """
(Keine Garantie für richtiges Zählen)"""

print(text.replace("\u200b", ""))

twapi.tweet(text)
