#!/usr/bin/python3

'''Helper for tweeting bot statistics'''

import argparse
import datetime
import logging
from Externals import setup_database, set_twitter_arguments, setup_twitter
import Mock
import Persistence

logger = Persistence.init_logger('statistics')

one_day = datetime.timedelta(days=1)
today = datetime.date.today()
first = today.replace(day=1)
january_first = first.replace(month=1)

parser = argparse.ArgumentParser(description=__doc__)
set_twitter_arguments(parser)
Persistence.set_logging_args(parser, 'INFO')
parser.add_argument('--since',
                    dest='since',
                    help='Time frame for statistics',
                    required=False,
                    choices=['0', 'month', 'year'],
                    default=0)
args = parser.parse_args()

logger.setLevel(getattr(logging, args.log_level))
logger.debug("statistics running args: %s", args)

if args.since == "0":
    since = 0
    since_text = 'Beginn'
elif args.since == 'month':
    since = (first - one_day).strftime("%Y%m01")
    since_text = 'Anfang letzten Monats'
elif args.since == 'year':
    since = (january_first - one_day).strftime("%Y0101")
    since_text = 'Anfang letzten Jahres'

twapi = setup_twitter(args)
if twapi is None:
    twapi = Mock.MockApi()
sql = setup_database(args)

counts = sql.count_status(since=since)
text = f"""Zeit für Statistik! Daten für die Zeit seit {since_text}. Ich habe:
• {counts.get('found', 0)} Kürzel beantwortet, für
• {counts.get('notfound', 0)} Kürzel keine lange Version erkannt und
• {counts.get('blacklist', 0)} nicht beantwortet, weil sie auf der Blacklist standen.

Die populärsten Kürzel waren:
"""

for row in sql.popular_abbrs(since):
    text += f"• {row['S']} ({row['C']}×)\n\u200b"
text += """
Die populärsten Quellen waren:
"""
for row in sql.popular_sources(since):
    text += f"• {row['S']} ({row['C']}×)\n\u200b"
text += """
(Keine Garantie für richtiges Zählen)"""

print(text.replace("\u200b", ""))

twapi.tweet(text)
