#!/bin/bash

pylint_score=$(\
    tools/check | \
    grep has\ been\ rated | \
    grep -o '[0-9]\+\.[0-9][0-9]' | \
    head -n 1 \
    )
test_result=$(./test --source testcases --output summary --log-level CRITICAL 2>&1)
pytest_result=$(python3 -m pytest tests/ --disable-warnings -q | head -n 1 | tr -s ' ')

echo "Adding pylint score $pylint_score..."
echo "...and test result $test_result..."
echo "...and pytest result $pytest_result..."
echo "...to commit message:"

git commit --allow-empty --amend -m "$(git log --format=%B -n1 | grep -v pylint\ score | grep -v test\ score | grep -v pytest\ score)

pylint score: $pylint_score
test score: $test_result
pytest score: $pytest_result"

git log --format=%B -n1
