#!/usr/bin/python3

"""Helper program for management of the bot blacklist"""

import argparse
from sys import stderr
import parentdir # pylint: disable=W0611
from Externals import setup_database

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--list', action='store_true', required=False, default=False)
parser.add_argument('--add', action='store', required=False)
# parser.add_argument('--remove', action='store', required=False)
parser.add_argument('--statistics-for', action='store', required=False)
parser.add_argument('--readwrite', help='Change Database', required=False, default=True)
args = parser.parse_args()

sql = setup_database(args)

if args.list:
    sql.cursor.execute("""
        SELECT
            source,
            Abk
        FROM
            blacklist
    """)
    for row in sql.cursor.fetchall():
        print(row['source'], row['Abk'])
    raise SystemExit(0)
if not args.statistics_for is None:
    print("Statistics for", args.statistics_for)
    sql.cursor.execute("""
        SELECT
            count(status) as c,
            status
        FROM
            requestlog
        WHERE
            abbreviation LIKE ?
        GROUP BY
            status
    """, (args.statistics_for, ))
    tot_sum = 0
    for row in sql.cursor.fetchall():
        tot_sum += row['c']
        print(row['c'], row['status'])
    print(tot_sum, "total")
    raise SystemExit(0)
if not args.add is None:
    sql.cursor.execute("""
        SELECT
            1
        FROM
            blacklist
        WHERE
            source || ':' || Abk = ?
    """, (args.add, ))
    row = sql.cursor.fetchone()
    if row is None:
        parts = args.add.split(':')
        sql.cursor.execute("""
            INSERT INTO
                blacklist(source, Abk)
            VALUES(?, ?)
        """, (parts[0], parts[1],))
        if sql.cursor.rowcount == 0:
            print("Keine Daten eingetragen", file=stderr)
            raise SystemExit(1)
        print("Erfolgreich eingetragen!")
        sql.close_sucessfully()
        raise SystemExit(0)
    print("Schon eingetragen!")
    raise SystemExit(0)
