#!/usr/bin/python3

"""Setup of data and documentation"""

import argparse
import logging
from pathlib import Path
import subprocess
import parentdir # pylint: disable=W0611
import Documentation
from Externals import setup_database
from GitVersion import Git
from Import import find_all_configs
import Persistence

logger = Persistence.init_logger('setup')

parser = argparse.ArgumentParser(description=__doc__)
Persistence.set_logging_args(parser, 'INFO')
parser.add_argument('--readwrite',
                    help='Actually do stuff',
                    required=False,
                    default=True)
args = parser.parse_args()

logger.setLevel(getattr(logging, args.log_level.upper()))
logger.debug("setup running args: %s", args)

output_dir = Path('output')
dump_dir = output_dir / 'dumps'
config_dir = Path('data')
doc_source = Path('doc')
cardsource = Path('cards')
Path.mkdir(dump_dir, parents=True, exist_ok=True)

database = setup_database(args, None)
database.purge_data()

configurations = find_all_configs(config_dir)
if configurations is None:
    raise SystemExit(1)
navilinks = Documentation.navilink_list(Git().describe('--dirty'))
dumplinks = Documentation.dumplink_list(configurations)

Documentation.create_documentation(navilinks, doc_source, output_dir)
Documentation.create_dump_mainpage(navilinks, dumplinks, dump_dir)
dRM = Documentation.MarkdownDoc(Path("data") / 'README.md', navilinks)
dRM.write(output_dir / 'data.html')
sRM = Documentation.MarkdownDoc(Path("sources") / 'README.md', navilinks)
sRM.write(output_dir / 'sources.html')

licpage = Documentation.Licenses(doc_source / 'copyright.md', navilinks)

for cid, config in sorted(configurations.items()):
    logger.info("Processing file %s", cid)
    is_default = True
    for a in config.access:
        database.insert_source(a, cid, is_default)
        is_default = False # only first one.
    for mht in config.magic_hashtags:
        database.insert_magic_hashtag(cid, mht)
    for dl in config.data_list:
        if not database.insert_datalist(dl, cid):
            raise SystemExit(1)
    Documentation.dump_source(config, dumplinks, navilinks, database, dump_dir)
    licpage.add_source(config)

licpage.write(output_dir / 'copyright.html')
Documentation.dump_blacklist(dumplinks, navilinks, database, dump_dir)
database.close_sucessfully()

subprocess.run(['chmod', '-R', 'ug=rwX,o=rX', str(output_dir)], check=False)
target_dir = Path('/var/www/ds100/')
avatar_dir = Path('/var/www/avatar/')
if target_dir.exists():
    subprocess.run(['rsync', '-a', str(output_dir) + "/", str(target_dir)], check=False)
    for fn in ('bot.css', 'mastodon-icon.png', 'twitter-icon.png', 'script.js'):
        subprocess.run(['rsync', '-a', str(doc_source / fn), str(target_dir)], check=False)
    subprocess.run(['rsync', '-a', str(cardsource / 'socialcard.png'), str(target_dir)],
            check=False)
else:
    logger.warning('Not copying documentation')
if avatar_dir.exists():
    subprocess.run(['rsync', '-a', str(doc_source / 'avatar.svg'), str(avatar_dir / 'ds100.svg')],
            check=False)
    subprocess.run(['rsync', '-a', str(doc_source / 'avatar-ril100.svg'), str(avatar_dir /
        'ril100.svg')], check=False)
else:
    logger.warning('Not copying avatar')

logger.info("Done")
