#!/bin/bash

cd $(git rev-parse --show-toplevel)

echo "Importing data…"
if ! tools/import-data; then
    echo "Abbruch"
    exit
fi
echo "Dumping…"
tools/dump

echo "Creating doc…"
cd doc/
. create.sh

tdir=/var/www/ds100
if [ -d "$tdir" ]; then
    echo "Copying data…"
    rsync -via output/ $tdir/
    rsync -via bot.css $tdir/
    chmod 664 $tdir/*.*
    chmod 664 $tdir/*/*.*
else
    echo "Not copying data"
fi

adir=/var/www/avatar
if [ -d "$adir" ]; then
    echo "Copying avatar…"
    chmod 664 avatar.svg
    cp avatar.svg $adir/ds100.svg
else
    echo "Not copying avatar"
fi
echo "Done"
